### ISSUE TITLE
运行的时候，出现错误了。。。

### ISSUE THREAD

**Issue by vvlaw** [HaujetZhao/ytb-vtt-to-srt#1]
vvlaw@archlinux  ~/ytb-vtt-to-srt   master  python3 油管vtt双行字幕转单行srt.py                                                                    1 ↵  4352  13:38:56

请输入 vtt 字幕路径：/mnt/SDCard/tv/youtube/1.vtt

command: ffmpeg -y -i "/mnt/SDCard/tv/youtube/1.vtt" "/mnt/SDCard/tv/youtube/1.srt"

Traceback (most recent call last):
  File "/home/vvlaw/ytb-vtt-to-srt/油管vtt双行字幕转单行srt.py", line 20, in <module>
    subprocess.call(command)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -y -i "/mnt/SDCard/tv/youtube/1.vtt" "/mnt/SDCard/tv/youtube/1.srt"'
 vvlaw@archlinux  ~/ytb-vtt-to-srt   master 

**Comment by vvlaw** [comment]
可以了 谢谢 非常好的工具

**Comment by vvlaw** [comment]
找到了解决的办法了。。。

1. 在lib文件夹中找到subprocess.py
2. 搜索class Popen(object):
3. 将__init__中的shell=False修改为shell=True
